version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: oven/bun:1.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - bun-cache-{{ checksum "bun.lockb" }}
            - bun-cache-
      - run:
          name: Install dependencies
          command: bun install
      - save_cache:
          name: Save cache
          key: bun-cache-{{ checksum "bun.lockb" }}
          paths:
            - ~/.bun
      - run:
          name: Lint files
          command: bun run lint
      - run:
          name: Build project
          command: bun run build
      - run:
          name: Make keys file
          command: echo ${TODO_KEYS} > keys.json
      - run:
          name: Deploy to Firebase Hosting
          command: |
            sudo bun install -g firebase-tools
            firebase deploy --only hosting
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: "keys.json"

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
